-- MySQL Workbench Synchronization
-- Generated: 2025-01-21 13:59
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: bovolato

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

ALTER TABLE `joalheria`.`produtos` 
DROP FOREIGN KEY `pedsubgrupo`;

ALTER TABLE `joalheria`.`produtos` 
ADD COLUMN `capa` LONGTEXT NULL DEFAULT NULL AFTER `em_reais`;

ALTER TABLE `joalheria`.`produtos` 
DROP FOREIGN KEY `cotprod2`;

ALTER TABLE `joalheria`.`produtos` ADD CONSTRAINT `cotprod2`
  FOREIGN KEY (`cotacao`)
  REFERENCES `joalheria`.`cotacoes` (`id`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `pedsubgrupo`
  FOREIGN KEY (`subgrupo_id`)
  REFERENCES `joalheria`.`subgrupo_produtos` (`id`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
