-- MySQL Script generated by MySQL Workbench
-- Fri Jan 17 12:08:02 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema joalheria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema joalheria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `joalheria` DEFAULT CHARACTER SET utf8 ;
USE `joalheria` ;

-- -----------------------------------------------------
-- Table `joalheria`.`grupo_clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joalheria`.`grupo_clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_grupo` VARCHAR(200) NOT NULL,
  `comissao_vendedores` DECIMAL(10,2) NULL DEFAULT 0.0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `joalheria`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joalheria`.`clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_cliente` VARCHAR(45) NULL,
  `nome_pf` VARCHAR(200) NULL DEFAULT NULL,
  `razao_social_pj` VARCHAR(200) NULL DEFAULT NULL,
  `nome_fantasia_pj` VARCHAR(200) NULL DEFAULT NULL,
  `perfil` VARCHAR(50) NULL DEFAULT NULL,
  `telefone` VARCHAR(20) NULL DEFAULT NULL,
  `whatsapp` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(200) NULL DEFAULT NULL,
  `rg` VARCHAR(50) NULL DEFAULT NULL,
  `cpf` VARCHAR(20) NULL DEFAULT NULL,
  `ie_pj` VARCHAR(50) NULL DEFAULT NULL,
  `cnpj_pj` VARCHAR(20) NULL DEFAULT NULL,
  `cep` VARCHAR(20) NULL DEFAULT NULL,
  `endereco` VARCHAR(200) NULL DEFAULT NULL,
  `bairro` VARCHAR(100) NULL DEFAULT NULL,
  `cidade` VARCHAR(100) NULL DEFAULT NULL,
  `estado` VARCHAR(50) NULL DEFAULT NULL,
  `data_nascimento` DATE NULL DEFAULT NULL,
  `tags` VARCHAR(200) NULL DEFAULT NULL,
  `origem_contato` VARCHAR(100) NULL DEFAULT NULL,
  `estado_civil` VARCHAR(50) NULL DEFAULT NULL,
  `corporativo` ENUM('S', 'N') NULL DEFAULT NULL,
  `grupo` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `grupo_idx` (`grupo` ASC),
  CONSTRAINT `grupo`
    FOREIGN KEY (`grupo`)
    REFERENCES `joalheria`.`grupo_clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `joalheria`.`fornecedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joalheria`.`fornecedores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `razao_social` VARCHAR(200) NOT NULL,
  `nome_fantasia` VARCHAR(200) NULL DEFAULT NULL,
  `cnpj` VARCHAR(20) NULL DEFAULT NULL,
  `insc_estadual` VARCHAR(50) NULL DEFAULT NULL,
  `insc_municipal` VARCHAR(50) NULL DEFAULT NULL,
  `condicao_pagto` VARCHAR(100) NULL DEFAULT NULL,
  `vigencia_acordo` DATE NULL DEFAULT NULL,
  `telefone` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(200) NULL DEFAULT NULL,
  `endereco` VARCHAR(200) NULL DEFAULT NULL,
  `cidade` VARCHAR(100) NULL DEFAULT NULL,
  `estado` VARCHAR(50) NULL DEFAULT NULL,
  `contato` VARCHAR(100) NULL DEFAULT NULL,
  `site` VARCHAR(200) NULL DEFAULT NULL,
  `banco` VARCHAR(100) NULL DEFAULT NULL,
  `numero_banco` VARCHAR(20) NULL DEFAULT NULL,
  `agencia` VARCHAR(20) NULL DEFAULT NULL,
  `conta` VARCHAR(20) NULL DEFAULT NULL,
  `pix` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `joalheria`.`cargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joalheria`.`cargos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cargo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `joalheria`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joalheria`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_completo` VARCHAR(200) NOT NULL,
  `email` VARCHAR(200) NULL DEFAULT NULL,
  `cargo` INT NOT NULL,
  `telefone` VARCHAR(20) NULL DEFAULT NULL,
  `rg` VARCHAR(50) NULL DEFAULT NULL,
  `emissao_rg` VARCHAR(50) NULL DEFAULT NULL,
  `cpf` VARCHAR(20) NULL DEFAULT NULL,
  `data_nascimento` DATE NULL DEFAULT NULL,
  `cep` VARCHAR(20) NULL DEFAULT NULL,
  `endereco` VARCHAR(200) NULL DEFAULT NULL,
  `cidade` VARCHAR(100) NULL DEFAULT NULL,
  `estado` VARCHAR(50) NULL DEFAULT NULL,
  `login` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `nivel_acesso` ENUM('Administrador', 'Operador', 'Consulta') NOT NULL,
  `bairro` VARCHAR(150) NULL,
  `numero` VARCHAR(150) NULL,
  PRIMARY KEY (`id`),
  INDEX `usucargo_idx` (`cargo` ASC),
  CONSTRAINT `usucargo`
    FOREIGN KEY (`cargo`)
    REFERENCES `joalheria`.`cargos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `joalheria`.`tipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joalheria`.`tipos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `joalheria`.`categoria_despesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joalheria`.`categoria_despesa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `joalheria`.`feriados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joalheria`.`feriados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_feriado` DATE NOT NULL,
  `descricao` VARCHAR(200) NOT NULL,
  `tipo` ENUM('Nacional', 'Municipal') NOT NULL,
  `facultativo` ENUM('S', 'N') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `joalheria`.`cartoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joalheria`.`cartoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_cartao` VARCHAR(200) NOT NULL,
  `taxa_administradora` DECIMAL(10,2) NULL DEFAULT 0.0,
  `tipo` ENUM('Crédito', 'Débito') NOT NULL,
  `bandeira` VARCHAR(100) NULL DEFAULT NULL,
  `max_parcelas` INT NULL DEFAULT NULL,
  `juros_parcela_1` DECIMAL(5,2) NULL DEFAULT NULL,
  `juros_parcela_2` DECIMAL(5,2) NULL DEFAULT NULL,
  `juros_parcela_3` DECIMAL(5,2) NULL DEFAULT NULL,
  `juros_parcela_4` DECIMAL(5,2) NULL DEFAULT NULL,
  `juros_parcela_5` DECIMAL(5,2) NULL DEFAULT NULL,
  `juros_parcela_6` DECIMAL(5,2) NULL DEFAULT NULL,
  `juros_parcela_7` DECIMAL(5,2) NULL DEFAULT NULL,
  `juros_parcela_8` DECIMAL(5,2) NULL DEFAULT NULL,
  `juros_parcela_9` DECIMAL(5,2) NULL DEFAULT NULL,
  `juros_parcela_10` DECIMAL(5,2) NULL DEFAULT NULL,
  `juros_parcela_11` DECIMAL(5,2) NULL DEFAULT NULL,
  `juros_parcela_12` DECIMAL(5,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `joalheria`.`grupo_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joalheria`.`grupo_produtos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_grupo` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `joalheria`.`subgrupo_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joalheria`.`subgrupo_produtos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_subgrupo` VARCHAR(200) NOT NULL,
  `grupo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `subgruidgru` (`grupo_id` ASC),
  CONSTRAINT `subgruidgru`
    FOREIGN KEY (`grupo_id`)
    REFERENCES `joalheria`.`grupo_produtos` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `joalheria`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joalheria`.`produtos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao_etiqueta` VARCHAR(200) NULL DEFAULT NULL,
  `fornecedor_id` INT NULL DEFAULT NULL,
  `categoria` VARCHAR(100) NULL DEFAULT NULL,
  `modelo` VARCHAR(100) NULL DEFAULT NULL,
  `material` VARCHAR(100) NULL DEFAULT NULL,
  `macica_ou_oca` VARCHAR(50) NULL DEFAULT NULL,
  `numeros` VARCHAR(100) NULL DEFAULT NULL,
  `pedra` VARCHAR(100) NULL DEFAULT NULL,
  `nat_ou_sint` VARCHAR(50) NULL DEFAULT NULL,
  `peso` DECIMAL(10,3) NULL DEFAULT NULL,
  `aros` VARCHAR(100) NULL DEFAULT NULL,
  `cm` DECIMAL(10,3) NULL DEFAULT NULL,
  `pontos` DECIMAL(10,3) NULL DEFAULT NULL,
  `mm` DECIMAL(10,3) NULL DEFAULT NULL,
  `detalhes` VARCHAR(500) NULL DEFAULT NULL,
  `grupo_id` INT NULL DEFAULT NULL,
  `subgrupo_id` INT NULL DEFAULT NULL,
  `unidade` VARCHAR(50) NULL DEFAULT NULL,
  `estoque_princ` DECIMAL(10,2) NULL DEFAULT NULL,
  `cotacao` DECIMAL(10,2) NULL DEFAULT NULL,
  `preco_ql` DECIMAL(10,2) NULL DEFAULT NULL,
  `peso_gr` DECIMAL(10,3) NULL DEFAULT NULL,
  `custo` DECIMAL(10,2) NULL DEFAULT NULL,
  `margem` DECIMAL(10,2) NULL DEFAULT NULL,
  `em_reais` DECIMAL(10,2) NULL DEFAULT NULL,
  `promocao` ENUM('S', 'N') NULL DEFAULT NULL,
  `inicio_prom` DATE NULL DEFAULT NULL,
  `termino_prom` DATE NULL DEFAULT NULL,
  `percentual_perda` DECIMAL(5,2) NULL DEFAULT NULL,
  `ultima_compra` DATE NULL DEFAULT NULL,
  `estoque` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `pedfor` (`fornecedor_id` ASC),
  INDEX `pedgrupo` (`grupo_id` ASC),
  CONSTRAINT `pedfor`
    FOREIGN KEY (`fornecedor_id`)
    REFERENCES `joalheria`.`fornecedores` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `pedgrupo`
    FOREIGN KEY (`grupo_id`)
    REFERENCES `joalheria`.`grupo_produtos` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `joalheria`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joalheria`.`pedidos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cliente_id` INT NOT NULL,
  `data_pedido` DATE NOT NULL,
  `forma_pagamento` VARCHAR(100) NULL DEFAULT NULL,
  `acrescimo` DECIMAL(10,2) NULL DEFAULT NULL,
  `observacoes` VARCHAR(500) NULL DEFAULT NULL,
  `total` DECIMAL(10,2) NULL DEFAULT NULL,
  `valor_pago` DECIMAL(10,2) NULL DEFAULT NULL,
  `desconto` DECIMAL(10,2) NULL DEFAULT NULL,
  `cod_vendedor` INT NULL DEFAULT NULL,
  `status_pedido` ENUM('Aberto', 'Pendente', 'Em andamento', 'Finalizado', 'Cancelado') NULL DEFAULT 'Aberto',
  `data_entrega` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `ped_cli` (`cliente_id` ASC),
  INDEX `ped_usu` (`cod_vendedor` ASC),
  CONSTRAINT `ped_cli`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `joalheria`.`clientes` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `ped_usu`
    FOREIGN KEY (`cod_vendedor`)
    REFERENCES `joalheria`.`usuarios` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `joalheria`.`pedidos_itens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joalheria`.`pedidos_itens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pedido_id` INT NOT NULL,
  `produto_id` INT NOT NULL,
  `quantidade` DECIMAL(10,2) NOT NULL,
  `valor_unitario` DECIMAL(10,2) NOT NULL,
  `desconto_percentual` DECIMAL(5,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `ped_id` (`pedido_id` ASC),
  INDEX `ped_prod` (`produto_id` ASC),
  CONSTRAINT `ped_id`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `joalheria`.`pedidos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ped_prod`
    FOREIGN KEY (`produto_id`)
    REFERENCES `joalheria`.`produtos` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `joalheria`.`fabrica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joalheria`.`fabrica` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pedido_id` INT NULL DEFAULT NULL,
  `data_solicitacao` DATE NULL DEFAULT NULL,
  `cliente_id` INT NULL DEFAULT NULL,
  `total` DECIMAL(10,2) NULL DEFAULT NULL,
  `data_inicio` DATE NULL DEFAULT NULL,
  `vendedor_id` INT NULL DEFAULT NULL,
  `posse` VARCHAR(100) NULL DEFAULT NULL,
  `status` ENUM('Aguardando Separacao', 'Em Producao', 'Finalizado') NULL DEFAULT 'Aguardando Separacao',
  `etapa_atual` VARCHAR(100) NULL DEFAULT NULL,
  `fila_producao` VARCHAR(100) NULL DEFAULT NULL,
  `data_entrega` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fabped` (`pedido_id` ASC),
  INDEX `fabcli` (`cliente_id` ASC),
  INDEX `fabusu` (`vendedor_id` ASC),
  CONSTRAINT `fabped`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `joalheria`.`pedidos` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fabcli`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `joalheria`.`clientes` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fabusu`
    FOREIGN KEY (`vendedor_id`)
    REFERENCES `joalheria`.`usuarios` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `joalheria`.`impressao_etiquetas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joalheria`.`impressao_etiquetas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `produto_id` INT NULL DEFAULT NULL,
  `solicitante` VARCHAR(200) NULL DEFAULT NULL,
  `quantidade` DECIMAL(10,2) NULL DEFAULT NULL,
  `layout_etiqueta` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `atiprod` (`produto_id` ASC),
  CONSTRAINT `atiprod`
    FOREIGN KEY (`produto_id`)
    REFERENCES `joalheria`.`produtos` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `joalheria`.`consignacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joalheria`.`consignacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cliente_id` INT NOT NULL,
  `data_consignacao` DATE NOT NULL,
  `valor` DECIMAL(10,2) NULL DEFAULT NULL,
  `status` ENUM('Aberta', 'Finalizada', 'Canceleda') NULL DEFAULT 'Aberta',
  `observacao` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `conseid` (`cliente_id` ASC),
  CONSTRAINT `conseid`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `joalheria`.`clientes` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `joalheria`.`consignacao_itens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joalheria`.`consignacao_itens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `consignacao_id` INT NOT NULL,
  `produto_id` INT NOT NULL,
  `quantidade` DECIMAL(10,2) NULL DEFAULT NULL,
  `valor` DECIMAL(10,2) NULL DEFAULT NULL,
  `qtd_devolvido` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `consid` (`consignacao_id` ASC),
  INDEX `contprod` (`produto_id` ASC),
  CONSTRAINT `consid`
    FOREIGN KEY (`consignacao_id`)
    REFERENCES `joalheria`.`consignacao` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `contprod`
    FOREIGN KEY (`produto_id`)
    REFERENCES `joalheria`.`produtos` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `joalheria`.`cotacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joalheria`.`cotacoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fornecedor_id` INT NOT NULL,
  `data_solicitacao` DATE NULL DEFAULT NULL,
  `validade_cotacao` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `cotfor` (`fornecedor_id` ASC),
  CONSTRAINT `cotfor`
    FOREIGN KEY (`fornecedor_id`)
    REFERENCES `joalheria`.`fornecedores` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `joalheria`.`cotacao_itens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joalheria`.`cotacao_itens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cotacao_id` INT NOT NULL,
  `produto_id` INT NOT NULL,
  `quantidade` DECIMAL(10,2) NULL DEFAULT NULL,
  `preco_cotado` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `cotid` (`cotacao_id` ASC),
  INDEX `cotprod` (`produto_id` ASC),
  CONSTRAINT `cotid`
    FOREIGN KEY (`cotacao_id`)
    REFERENCES `joalheria`.`cotacoes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `cotprod`
    FOREIGN KEY (`produto_id`)
    REFERENCES `joalheria`.`produtos` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `joalheria`.`entrada_mercadorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joalheria`.`entrada_mercadorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nf_fiscal` VARCHAR(50) NULL DEFAULT NULL,
  `data_pedido` DATE NULL DEFAULT NULL,
  `fornecedor_id` INT NULL DEFAULT NULL,
  `data_prevista_entrega` DATE NULL DEFAULT NULL,
  `status_entrega` VARCHAR(100) NULL DEFAULT NULL,
  `data_entregue` DATE NULL DEFAULT NULL,
  `transportadora` VARCHAR(200) NULL DEFAULT NULL,
  `valor` DECIMAL(10,2) NULL DEFAULT NULL,
  `observacoes` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `entradafor` (`fornecedor_id` ASC),
  CONSTRAINT `entradafor`
    FOREIGN KEY (`fornecedor_id`)
    REFERENCES `joalheria`.`fornecedores` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `joalheria`.`estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joalheria`.`estoque` (
  `id` INT NOT NULL,
  `produtos_id` INT NULL,
  `entrada_mercadorias_id` INT NULL,
  `quantidade_minima` DECIMAL(5,2) NULL,
  `quantidade` DECIMAL(8,2) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_estoque_produtos1_idx` (`produtos_id` ASC),
  INDEX `fk_estoque_entrada_mercadorias1_idx` (`entrada_mercadorias_id` ASC),
  CONSTRAINT `fk_estoque_produtos1`
    FOREIGN KEY (`produtos_id`)
    REFERENCES `joalheria`.`produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estoque_entrada_mercadorias1`
    FOREIGN KEY (`entrada_mercadorias_id`)
    REFERENCES `joalheria`.`entrada_mercadorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `joalheria`.`movimentacao_estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joalheria`.`movimentacao_estoque` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `observacao` TEXT NULL DEFAULT NULL,
  `tipo_movimentacao` ENUM('Entrada', 'Saida', 'Ajuste') NOT NULL,
  `quantidade` DECIMAL(10,2) NOT NULL,
  `documento` VARCHAR(50) NULL DEFAULT NULL,
  `data_movimentacao` DATE NOT NULL,
  `estoque_antes` DECIMAL(10,2) NULL DEFAULT NULL,
  `estoque_atualizado` DECIMAL(10,2) NULL DEFAULT NULL,
  `estoque_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_movimentacao_estoque_estoque1_idx` (`estoque_id` ASC),
  CONSTRAINT `fk_movimentacao_estoque_estoque1`
    FOREIGN KEY (`estoque_id`)
    REFERENCES `joalheria`.`estoque` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `joalheria`.`financeiro_contas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joalheria`.`financeiro_contas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fornecedor_id` INT NULL,
  `cliente_id` INT NULL,
  `categoria_id` INT NULL DEFAULT NULL,
  `data_vencimento` DATE NOT NULL,
  `valor` DECIMAL(10,2) NULL DEFAULT NULL,
  `data_pagamento` DATE NULL DEFAULT NULL,
  `status` ENUM('Pago', 'Pendente') NULL DEFAULT 'Pendente',
  `observacao` VARCHAR(500) NULL DEFAULT NULL,
  `recorrente` ENUM('S', 'N') NULL DEFAULT 'N',
  `tipo` VARCHAR(45) NOT NULL,
  `num_parcelas` INT NULL,
  `val_par1` DECIMAL(10,2) NULL,
  `dt_par1` DATE NULL,
  `val_par2` DECIMAL(10,2) NULL,
  `dt_par2` DATE NULL,
  `val_par3` DECIMAL(10,2) NULL,
  `dt_par3` DATE NULL,
  `val_par4` DECIMAL(10,2) NULL,
  `dt_par4` DATE NULL,
  `val_par5` DECIMAL(10,2) NULL,
  `dt_par5` DATE NULL,
  `val_par6` DECIMAL(10,2) NULL,
  `dt_par6` DATE NULL,
  `val_par7` DECIMAL(10,2) NULL,
  `dt_par7` DATE NULL,
  `val_par8` DECIMAL(10,2) NULL,
  `dt_par8` DATE NULL,
  `val_par9` DECIMAL(10,2) NULL,
  `dt_par9` DATE NULL,
  `val_par10` DECIMAL(10,2) NULL,
  `dt_par10` DATE NULL,
  `val_par11` DECIMAL(10,2) NULL,
  `dt_par11` DATE NULL,
  `val_par12` DECIMAL(10,2) NULL,
  `dt_par12` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `finfor` (`fornecedor_id` ASC),
  INDEX `fincat` (`categoria_id` ASC),
  INDEX `cliid_idx` (`cliente_id` ASC),
  CONSTRAINT `finfor`
    FOREIGN KEY (`fornecedor_id`)
    REFERENCES `joalheria`.`fornecedores` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fincat`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `joalheria`.`categoria_despesa` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `cliid`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `joalheria`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `joalheria`.`comissao_vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joalheria`.`comissao_vendedor` (
  `id` INT NOT NULL,
  `caomissao` DECIMAL(3,2) NULL,
  `comissao_vendedorcol` VARCHAR(45) NULL,
  `grupo_produtos_id` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comissao_vendedor_grupo_produtos1_idx` (`grupo_produtos_id` ASC),
  INDEX `fk_comissao_vendedor_usuarios1_idx` (`usuarios_id` ASC),
  CONSTRAINT `fk_comissao_vendedor_grupo_produtos1`
    FOREIGN KEY (`grupo_produtos_id`)
    REFERENCES `joalheria`.`grupo_produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comissao_vendedor_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `joalheria`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
