services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: joalheria_web      
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: joalheria
      DB_USER: root
      DB_PASS: root
      DB_PORT: "3306"
  db:
    image: mysql:8.0
    container_name: joalheria_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: joalheria
    volumes:
      - db_data:/var/lib/mysql  # Adicionado volume para persistência
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: allivo_phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db

networks:
  app_network:
    name: joalheria_network
    driver: bridge

volumes:
  db_data:  
    name: joalheria_db_data